---
title: "Project Protocol"
output:
  pdf_document:
    toc: yes
    number_sections: yes
  word_document:
    toc: yes
bibliography: protocol.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



#	Title
Assessing the effectiveness of hexagon tile maps for communicating spatial distributions of disease for Australia.

#	Project team roles & responsibilities

|          Researcher          |    Role                    |    Affiliation                                                                |   |   |
|:----------------------------:|----------------------------|-------------------------------------------------------------------------------|---|---|
|    Stephanie Kobakian        |    Masters Student         | Faculty of Science and Engineering (QUT)                                      |   |   |
|    Prof. Kerrie Mengersen    |    Principal Supervisor    | Faculty of Science and Engineering (QUT)                                      |   |   |
|    Dr. Earl Duncan           |    Associate Supervisor    | Faculty of Science and Engineering (QUT)                                      |   |   |
|    Prof. Dianne Cook         |    External Supervisor     |    Department of Econometrics and   Business Statistics, Monash University    |   |   |
|                              |                            |                                     


 
#	Background information

##	Project outline

This project will test the effectiveness of two types of spatial displays: a choropleth map, and a hexagon map. It will contrast the effectiveness of communicating information when each geographic region is represented by a hexagon, rather than its geographical shape. The purpose of these displays is to convey the spatial distribution of the disease occurrence, or incidence. This can allow for detecting hot spots corresponding to outbreaks, or spatial trends, for example, indicating occurrence is related to rural vs urban differences or localised to a single population dense region. Effectiveness of the display will be measured by accurate and efficient detection of these patterns.

##	Introduction/background information

@ACTUC suggests alternative map displays that aim for ‘equitable representation design’ present each member of a society equally. They are considered more ‘socially just’ but also help to present an honest display of the experiences of the whole population [@NISCC]. This work aims to determine if using a coloured hexagon display is a more effective method of communicating the spatial relationship between a set of areas on a map. 

##	Rationale/justification

This work is motivated by the newly developed Australian Cancer Atlas where information regarding cancer incidence and mortality is provided to the community through a web page. We are interested to know whether providing the spatial distribution in a hexagon map is more effective for communication than the traditional choropleth map.
The responses of participants will be contrasted when shown the same information in both a geographic and hexagon map display and asked to find the same real distribution in a collection of maps arranged in a line up. The rate of participants who pick the maps in the line ups that display the true spatial relationship will be used to contrast the effectiveness of the displays. We hope that this will show a hexagon map is an effective method for communicating spatial relationships.

#	Study objectives

##	Hypotheses

A hexagon tile map display allows people to detect the impact of a disease in highly populated small areas with higher accuracy and efficiency, in comparison to the accuracy and efficiency of detections made when viewing a choropleth map.

##	Research questions/ aims

1. Are spatial disease trends, that impact highly populated small areas,  detected with higher accuracy when viewed in a hexagon tile map display?
2. Are people faster in detecting spatial disease trends, that impact highly populated small areas, when using a hexagon tile map display?
3. Do people find hexagon tile maps more difficult to read than choropleth maps?
4. Are the reasons for choosing a plot different depending on the type of display?
5. Does an Australian resident find the choropleth map easier to read than the hexagon tile map?


##	Outcome measures 

For each plot evaluation the subject will provide these responses:

- Their choice of plot from a lineup
- Reason for choice of plot
- Time taken to respond
- Perceived difficulty in making a choice

#	Study design

Each participant will first see three test displays, they will then undertake an online survey linked to them through the online crowdsource platform Figure-Eight.
Within the experiment:
A line up protocol will be used to arrange 20 maps into one display.
Each display will be created by a combination of plot type, error distribution and spatial dependence.
We will contrast the sets of different plot designs, hexagon tilemap and geography in the lineups created using the same data, and same null positions within the lineup. 
We will compare the length of time taken and the accuracy with which participants report their choice.

The levels of the factors are:

 - Plot type: Geography, Hexagons
 - Spatial Dependence: Difference in a single city, Related to population density, North to South

Allowing each factor combination to be considered will provide 12 (2x2x3) line up displays to be seen by all participants.

#	Study population

##	Participants
We will aim to survey 100 participants.
It will be advertised to potential participants via their dashboard through their Figure-Eight accounts. 

##	Inclusions and exclusion criteria
The platform will advertise this survey to participants that fulfill the following:
 - level 2 or level 3 on the Figure-Eight Platform. 
 - at least 18 years old
 - trained and qualified to annotating images. 

##	Recruitment strategies, timeframe 
Recruitment will take place via advertising on the Figure-Eight dashboards.
The Figure-Eight platform will advertise this as a “job” to potential participants, they will not be under any obligation to complete this task. We will have the opportunity to wait until enough participants have completed the survey and provided their judgements.



##	Consent approaches

Participants will be shown instructions which will provide sufficient information about the task when they select to do the survey. These instructions will explain the survey to participants, and give them an example of the questions they will answer. 
Contact information for the researchers will be made available to the participants.
Participants will be asked to provide consent via a checkbox question.
They will then continue to the survey, and complete the test questions.
This page will also explain the use and storage of the data they contribute. The data will be the answers they provide, which will be publicly available on github at https://github.com/srkobakian/experiment. 

##	Participant withdrawal
Participants will be able to withdraw by leaving the survey at any time.

#	Procedures

##	Screening of participants
Participants will need to have achieved contributor level two on the Figure-Eight platofrm, this is a smaller group of more experienced, higher accuracy contributors.
Test questions are the most important quality control mechanism in the Figure-Eight Platform. Participants will complete them to practice and prepare for the experiment questions, they will need to reach an accuracy threshold we will set, to be allowed to participate in answering the experiment survey questions.

Contributors that fail quiz mode are not paid and are permanently disqualified from working on your job. Participants will need to reach an accuracy threshold we will set to be allowed to answer the questions in our survey. Test questions will also be included as the job progresses so we can be sure quality remains high.

##	Data collection

As the survey is conducted through the Figure-Eight platform, IP Address Contributor ID, Trust Score and Channel(add link to Figure 8 details page ) will be provided. In addition to the experimental design and response variables:
 
- Plot type ( Hexagon / Geographic )
- Trend model ( Two hotspots / Multiple hotspots / spatial trend )
- Choice of plot in each line up
- Reason for choice of plot
- Time taken to answer
- Perceived difficulty of question
 
the survey of participants will provide this demographic information:

- Gender (female / male / other),
- Degree education level achieved (high school / bachelors / masters / doctorate / other),
- Age range (18-24 / 25-34 / 35-44 / 45-54 / 55+ / other)
- Lived in Australia (Yes / No / other)

##	Data collection/gathering techniques: 
Data will be collected through survey distribution via a web application.
Participants will access the application via link from a Figure-Eight "job".

##	Impact of, and response to, missing data
If participants want to provide and "I don't know" answer they will be able to select this.
If there are more than 50% of questions that are incomplete we will remove this survey and consider this withdrawal.

 
#	Statistical plan

The design of this study is based on work by Hofmann, Follett, Majumder and Cook [-@GTPCCD]. 

##	Sample size determination and power; or how will determine that data saturation has occurred or data are sufficient for the purpose.

To be able to effectively evaluate the use of a hexagon tilemap we will contrast the proportion of times the real data plot was chosen in a line up of maps.
The same data will be used to create 19 null data plots and one real data plot. This data will be displayed to users in both geographic maps and hexagon tile maps.

We will have aim to collect results from 100 participants (n=100), who will have tried to pick the real data in a line up of simulated data. 

Let X be the corresponding random variable X, where i.e. X = # times out of n independent repetitions that the data plot is picked from the lineup.

Under the null hypothesis, X has a Binomial distribution: $X ~ B_{n,1=m}$. 
The p-value of a lineup is the probability to have x or more observers picking the data plot, under the assumption that the null hypothesis is true:
$p-value = P(X \geq x|H_0) = 1- B_{n,1/m}(x-1)$

This sets our Type I error rate, $\alpha$, at a level of $1/m$.
The authors also define how to estimate the power of a lineup: the ratio of correct identifications of the real data, x, out of n viewings.



##	Data analysis and Statistical methods


This will be analysed using a generalised linear model, with random effects capturing the differences between the 100 participants.
The main effects used will consider the spatial distribution of the errors, gender, degree education level achieved, age range and whether the participant has lived in Australia.


Each lineup will have similar hypotheses:
$H_0:$ there is no real structure visible in the data plot
$H_1:$ there is real structure visible in the data plot

Each lineup is a set of m = 20 plots.
One plot contains data with a real structure.
The probability that an observer picks the data plot when it is really *not* different from the 19 null plots, is $1/m = 1/20$.

If a participant is able to identify the data plot from the lineup, we reject the null hypothesis.
Type I error rate, $\alpha$, is set to a level of $1/m = 1/20 = 0.05$.


Compare the percentage of times users select the real data in a lineup for the same set of data presented in choropleth maps and hexagon tile maps.
Compare percentages of correct responses $\hat{\pi}_C$ and $\hat{\pi}_H$:

Where $C$ denotes the use of choropleth maps and $H$ denotes the use of hexagon tile maps.

The percentage of correct responses where the respondent identified the real data in a choropleth map is denoted by $\hat{\pi}_C = (x_C +1)/(n_{100} + 1)$, similarly for hexagon tile maps: $\hat{\pi}_H = (x_H +1)/(n_{100} + 1)$.


#	Outcome measures

## Response variables 

### Accuracy

To measure the accuracy of the detections, the plot chosen for each lineup evaluated will be compared to the position of the real spatial trend plot in the lineup.

A correct result occurs when the chosen plot matches the position of the real plot, this will be recorded in an additional binary variable; $1 = correct;~ 0 = incorrect$.


### Efficiency

High efficiency occurs when a small amount of time is taken to evaluate each lineup.
This will be measured as the numeric variable measuring the length of time taken to submit the answers to the evaluation of each line up.

## Model

A multilevel linear model with be fitted to the data with elements as specified below. 

Response Variables:
Accuracy and Efficiency 

Main Effects:
Design, Trend

Random Effects:
The collection of multiple responses from each person as they complete several different lineup tasks, allows estimates of their perceptual ability using a subject-specific random intercept in a generalized linear model.

Possible Interactions:
Design and Trend, Design and Difficulty, Design and Reason

Possible covariates:
Responses to the questions regarding the difficulty of making a choice and the reason for the choice of plot in the line up.

#	Data management and record keeping

Research expectations today require that publications use reproducible research protocols, requiring data to be available. De-identified, and privatised data will be made available will be made available via QUT's Research Data Finder, and, if required by the publisher, once the results are published also available on the journal article web site.


##	Confidentially and privacy

Datasets produced from the project and that will *not* be available for public access will contain original demographic information about the participants and only the anonymous Figure-Eight contributor ID. 

Datasets produced from the project and that *will be* available for public access on github will be de-identified and only contain the responses to survey.
If there are participants with unique sets of demographics, their data will be combined with larger categories to minimise the risks of reidentification.


##	Data security

Responses to the survey will be stored securely using a private google drive accessible only to the researchers during the study through their password protected google drive accounts. This will contain the demographic information, at the coarse resolution specified in the data collection.

##	Record retention

To ensure records are retained during and following the study the responses will be stored on the google drive immediately following the submission by participants. At the conclusion of the survey, the data will remain in the password protected google drive account.

During the analysis phase the researchers Stephanie and Dianne will make copies of the survey responses to their work devices (laptop computers), that are password protected.

This data set will also be de-identified, by removing the demographic data, and saved on the QUT network drives, which are automatically backed-up nightly in two physical locations. The records of data analysis undertaken and the de-identified data will be stored on github as well as on QUT network drives. 

##	Secondary use 

The analysis scripts and the de-identified data will be available for secondary use by other researchers to reproduce these results and also use in future studies. Participants will be asked to provide consent for this usage in the consent form.  

#	Resources
This work will be supported by ACEMS funding - $500 to pay 100 participants equally.

#	Results, outcomes and future plans
 - Plans for return of results of research to participants
 - Publication plan
 - Other potential uses of the data at the end of the project
 - Project closure processes 
 - Plans for sharing and/or future use of data and/or follow-up research 

#	References

#	Appendices 
 - These may include surveys, questionnaires, interview schedules, recruitment materials, manual of operations, etc 
